#
# JDBC properties
#
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee_directory
    username: springstudent
    password: springstudent
  security:
    user:
      name: carlos
      password: test123

logging:
  level:
    org:
      springframework:
        security: DEBUG